name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build app
      run: g++ app.cpp -o app

    - name: Build test
      run: g++ test.cpp -o test

    - name: Run test
      run: ./test
